# This file is a template, and might need editing before it works on your project.
# This file is a template, and might need editing before it works on your project.
stages:
  - build-image
  - run-image

build-image:
  stage: build-image
  script:
    - docker build -t "$CI_PROJECT_PATH_SLUG" .
run-image:
  stage: run-image
  script:
    - echo "$CI_PROJECT_PATH_SLUG"
    - nvidia-docker run --gpus all -v ${PWD}:/app "$CI_PROJECT_PATH_SLUG"
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
  artifacts:
    paths:
      - "*"
